annotations:
  application.giantswarm.io/team: robots
apiVersion: v2
appVersion: 0.2.3
dependencies:
- name: common
  repository: "file://charts/common"
  version: 4.3.0
description: A Helm chart for the Hashicorp HTTP Echo application
home: https://github.com/haraldkoch/helm-charts/tree/main/charts/echo
icon: https://secure.gravatar.com/avatar/f7304a610df968cef5badc9e9dcd40e0.jpg?s=80&r=g&d=mm
keywords:
- echo
- http-echo
maintainers:
- email: harald.koch@gmail.com
  name: haraldkoch
name: http-echo
sources:
- https://hub.docker.com/r/hashicorp/http-echo/
- https://github.com/hashicorp/http-echo
type: application
version: 0.3.2
